import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navabar";
import { AuthProvider } from "./context/authContext";
import Footer from "./components/Footer";
import ColorGrid from "./components/ColorGrid";

export const metadata: Metadata = {
  title: "yourHR",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` font-Raleway`}>
        <div className="mx-auto max-w-6xl h-auto">
          <AuthProvider>
            <ColorGrid />
            <Navbar />
            {children}
            <Footer />
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
